#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

APP_VERSION = 1.51

aboutmsg = """
PyNSource GUI

Version %s

A GUI front end to the python code scanner PyNSource that generates UML diagrams from Python Source code.

(c) Andy Bulka 2004-2011
http://www.andypatterns.com/index.php/products/pynsource/

License: GPL 3 (free software).
""" % APP_VERSION

import wx
import wx.lib.ogl as ogl
import sys
import os
import argparse

from pynsource import pynsourcegui


def argparser():
  rootparser = argparse.ArgumentParser(prog='haystack-reversers', description='Do a iterative pointer search to find structure.')
  rootparser.add_argument('filename', type=argparse.FileType('r'), default=None, action='store', help='python file to parse.')
  rootparser.set_defaults(func=mainloop)  
  return rootparser

def mainloop(opts):

  application = pynsourcegui.BoaApp(0)
  ogl.OGLInitialize()

  if opts.filename is not None:
    application.win.Go(files=[opts.filename.name  ])
    application.win.redraw2()  #ADDED AT MAC PORT TIME
    application._HackToForceTheScrollbarToShowUp()
      
#----------------------------------------------------------------------
  application.MainLoop()

def main(argv):
  parser = argparser()
  opts = parser.parse_args(argv)
  
  opts.func(opts)  
  
if __name__ == '__main__':
  main(sys.argv[1:])


