#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

APP_VERSION = 1.51

aboutmsg = """
PyNSource GUI

Version %s

A GUI front end to the python code scanner PyNSource that generates UML diagrams from Python Source code.

(c) Andy Bulka 2004-2011
http://www.andypatterns.com/index.php/products/pynsource/

License: GPL 3 (free software).
""" % APP_VERSION

import wx
import wx.lib.ogl as ogl
from pynsource import pynsourcegui

def main():
    application = pynsourcegui.BoaApp(0)
#----------------------------------------------------------------------
# This creates some pens and brushes that the OGL library uses.

    ogl.OGLInitialize()

#----------------------------------------------------------------------
    application.MainLoop()


if __name__ == '__main__':
    main()



